services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"

  backend:
    build: 
      context: ./backend
    ports:
      - "3001:3001"
    environment: 
      - NODE_ENV=production
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npx sequelize-cli db:migrate && npx sequelize-cli db:seed:all && npm start"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blogdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d blogdb -U user"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

volumes:
  pgdata: