

services:
  web:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment: 
      - NODE_ENV=production
    depends_on:
      - db
    command: sh -c "npx sequelize-cli db:migrate && npx sequelize-cli db:seed:all && npm start"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blogdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: